### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by gnusec** [Patitotective/ImPasswordGen#1]
`nimble install https://github.com/Patitotective/ImPasswordGen
`

Error:
```
/tmp/nimble_2687577/githubcom_PatitotectiveImPasswordGen_#head/src/prefsmodal.nim(5, 22) Error: cannot open file: niprefs/utils
       Tip: 217 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: ImPasswordGen
        ... Execution failed with exit code 1

```

`nim --version`
`Nim Compiler Version 1.6.6 [Linux: amd64`

**Comment by Patitotective** [comment]
ImPasswordGen was a pretty naive project I made to start with Dear ImGui, thus it's pretty old and since then some dependencies have updated and the code broke. Though, I'd like to get ImPassword working before I archive it, so probably tomorrow I'll release the last version of ImPasswordGen fixing this issue.
Thanks for reporting the issue.

**Comment by Patitotective** [comment]
It should be fixed as of https://github.com/Patitotective/ImPasswordGen/releases/tag/0.3.0.

**Comment by gnusec** [comment]
Your work is valuable. I looked at every nim gui project I could find. Only ImTemplate and fidget currently seem to be more usable. keep going bro.
